# Generated by Django 3.2.2 on 2021-05-12 03:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0003_rename_paymentmethod_payment'),
    ]

    operations = [
        migrations.AddField(
            model_name='payment',
            name='reasoning',
            field=models.CharField(default=0, max_length=100),
            preserve_default=False,
        ),
    ]
