# Generated by Django 3.2.2 on 2021-05-12 03:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0004_payment_reasoning'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Payment',
            new_name='PaymentMethod',
        ),
    ]
