# Generated by Django 3.2.2 on 2021-06-04 23:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0006_shirt'),
    ]

    operations = [
        migrations.AddField(
            model_name='shirt',
            name='brand',
            field=models.CharField(default=0, max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='shirt',
            name='size',
            field=models.CharField(default=0, max_length=2),
            preserve_default=False,
        ),
    ]
