# Generated by Django 3.2.2 on 2021-06-04 23:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0008_auto_20210604_2319'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Pant',
            new_name='Shirt',
        ),
    ]
