# Generated by Django 3.2.2 on 2021-06-25 04:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0002_remove_book_author'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='author',
            name='last_name',
        ),
    ]
