# Generated by Django 3.2.2 on 2021-06-26 04:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0003_remove_author_last_name'),
    ]

    operations = [
        migrations.RenameField(
            model_name='author',
            old_name='first_name',
            new_name='fname',
        ),
    ]
