# Generated by Django 3.2.2 on 2021-06-26 04:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0004_rename_first_name_author_fname'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='color',
            field=models.CharField(default=0, max_length=30),
            preserve_default=False,
        ),
    ]
