# Generated by Django 3.2.2 on 2021-06-26 04:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0005_book_color'),
    ]

    operations = [
        migrations.RenameField(
            model_name='book',
            old_name='color',
            new_name='colour',
        ),
    ]
