# Generated by Django 3.2.2 on 2021-05-12 02:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reporters', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='article',
            name='reporter',
        ),
        migrations.DeleteModel(
            name='Reporter',
        ),
    ]
