# Generated by Django 3.2.2 on 2021-05-12 06:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reporters', '0003_auto_20210512_0255'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='mood',
            field=models.CharField(default=0, max_length=100),
            preserve_default=False,
        ),
    ]
