# Generated by Django 3.2.2 on 2021-05-12 06:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reporters', '0004_article_mood'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Article',
            new_name='Essay',
        ),
    ]
