# Generated by Django 3.2.2 on 2021-05-12 06:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reporters', '0005_rename_article_essay'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Essay',
            new_name='Article',
        ),
    ]
