# Generated by Django 3.2.2 on 2021-05-12 16:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reporters', '0009_remove_article_mood'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='article',
            name='reporter',
        ),
        migrations.AddField(
            model_name='article',
            name='reporter',
            field=models.ManyToManyField(to='reporters.Reporter'),
        ),
    ]
