# Generated by Django 3.2.2 on 2021-05-12 16:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reporters', '0010_auto_20210512_1625'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='article',
            name='reporter',
        ),
        migrations.AddField(
            model_name='article',
            name='reporters',
            field=models.ManyToManyField(related_name='articles', to='reporters.Reporter'),
        ),
    ]
