# Generated by Django 3.2.2 on 2021-05-13 01:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reporters', '0011_auto_20210512_1646'),
    ]

    operations = [
        migrations.RenameField(
            model_name='article',
            old_name='reporters',
            new_name='reporter',
        ),
    ]
