# Generated by Django 3.2.2 on 2021-05-13 01:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reporters', '0012_rename_reporters_article_reporter'),
    ]

    operations = [
        migrations.RenameField(
            model_name='article',
            old_name='reporter',
            new_name='reporters',
        ),
    ]
