# Generated by Django 3.2.2 on 2021-05-13 01:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reporters', '0013_rename_reporter_article_reporters'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='article',
            name='reporters',
        ),
    ]
