# Generated by Django 3.2.2 on 2021-05-13 02:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reporters', '0014_remove_article_reporters'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='reporters',
            field=models.ManyToManyField(related_name='articles', to='reporters.Reporter'),
        ),
    ]
