# Generated by Django 3.2.2 on 2021-05-13 02:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reporters', '0015_article_reporters'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='reporters',
            field=models.ManyToManyField(related_name='article', to='reporters.Reporter'),
        ),
    ]
