# Generated by Django 3.2.2 on 2021-05-13 02:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reporters', '0016_alter_article_reporters'),
    ]

    operations = [
        migrations.CreateModel(
            name='Writer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=30)),
                ('last_name', models.CharField(max_length=30)),
                ('email', models.EmailField(max_length=254)),
            ],
        ),
        migrations.AlterField(
            model_name='article',
            name='reporters',
            field=models.ManyToManyField(related_name='article', to='reporters.Writer'),
        ),
    ]
