# Generated by Django 3.2.2 on 2021-05-13 02:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reporters', '0017_auto_20210513_0237'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='article',
            name='reporters',
        ),
        migrations.DeleteModel(
            name='Writer',
        ),
    ]
