# Generated by Django 3.2.2 on 2021-05-30 20:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reporters', '0020_shirt_size'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Shirt',
        ),
    ]
