# Generated by Django 3.2.2 on 2021-05-30 20:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reporters', '0022_pant'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Pant',
        ),
    ]
