# Generated by Django 3.2.2 on 2021-05-30 21:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reporters', '0024_pant'),
    ]

    operations = [
        migrations.CreateModel(
            name='Laptop',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('color', models.CharField(max_length=100)),
                ('brand', models.CharField(max_length=100)),
            ],
        ),
    ]
