# Generated by Django 3.2.2 on 2021-05-30 21:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reporters', '0025_laptop'),
    ]

    operations = [
        migrations.CreateModel(
            name='Computer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('brand', models.CharField(max_length=100)),
            ],
        ),
    ]
