# Generated by Django 3.2.2 on 2021-05-30 21:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reporters', '0027_auto_20210530_2119'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Laptop',
        ),
    ]
